all: apartment0.set0.m4 bar.set0.m4 job.set0.m4
	@m4 apartment0.set0.m4 > apartment0.set0
	@m4 bar.set0.m4 > bar.set0
	@m4 job.set0.m4 > job.set0

clean:
	@rm apartment0.set0 
	@rm bar.set0
	@rm job.set0
