all: apartment0.set.m4 bar.set.m4 job.set.m4
	@m4 apartment0.set.m4 > apartment0.set
	@m4 apartmentblock.set.m4 > apartmentblock.set
	@m4 apartmentblock.positioned.m4 > apartmentblock.positioned
	@m4 bar.set.m4 > bar.set
	@m4 job.set.m4 > job.set

clean:
	@rm -f apartment0.set apartmentblock.set apartmentblock.positioned bar.set job.set
