all: apartment0.set.m4 bar.set.m4 job.set.m4
	@m4 apartment0.set.m4 > apartment0.set
	@m4 apartmentblock.set.m4 > apartmentblock.set
	@m4 apartmentblock.positioned.m4 > apartmentblock.positioned
	@m4 bar.set.m4 > bar.set
	@m4 job.set.m4 > job.set

clean:
	@rm apartment0.set 
	@rm apartmentblock.set
	@rm apartmentblock.positioned
	@rm bar.set
	@rm job.set
